
from time import sleep
import pyautogui


#attribution d'un nom aux vlan
sleep(5)
pyautogui.typewrite("en")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("conf t")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)

pyautogui.typewrite("vlan 10")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("name Windows")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("exit")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)

pyautogui.typewrite("vlan 20")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("name Client")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("exit")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)

pyautogui.typewrite("vlan 30")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("name Linux")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("exit")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)


#configuration vlan access et trunk
pyautogui.typewrite("Interface FastEthernet 0/1")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("switchport access VLAN 10")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("exit")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)

pyautogui.typewrite("Interface FastEthernet 0/2")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("switchport access VLAN 20")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("exit")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)

pyautogui.typewrite("Interface FastEthernet 0/3")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("switchport access VLAN 30")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("exit")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)

pyautogui.typewrite("Interface FastEthernet 0/24")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("switchport mode trunk")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("switchport trunk allowed vlan all")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("exit")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)

pyautogui.typewrite("exit")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
pyautogui.typewrite("write")
sleep(0.2)
pyautogui.press('enter')
sleep(0.2)
